custom: ['https://www.buymeacoffee.com/manerakai'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
liberapay: simplytranslate_mobile # Replace with a single Liberapay username
